### PR TITLE
contrid: add nvidia infomation widget type

### PR DESCRIPTION
**Pull request by shadowmourne**
Give a way to monitoring utilization, temperature and frequency of NVIDIA GPUs using NVIDIA proprietary driver.

### CODE REVIEW

**Comment by Mic92** [comment]
Do you think it is useful to have both: nvsmi.lua and nvinf.lua

**Comment by shadowmourne** [comment]
Yes, it's useful.

As the nvidia-smi documents said, nvidia-smi have only limited support for Geforce products except Titan.
```
Supported products:
- Full Support
    - All Tesla products, starting with the Fermi architecture
    - All Quadro products, starting with the Fermi architecture
    - All GRID products, starting with the Kepler architecture
    - GeForce Titan products, starting with the Kepler architecture
- Limited Support
    - All Geforce products, starting with the Fermi architecture
```

For me, using GeForce GTX 680M, nvidia-smi can not get information about utilization and clock, but nvidia-settings can.

**Comment by Mic92** [comment]
Ok, can nvidia-settings replace nvidia-smi or in other words, if  nvidia-smi is available, nvidea-settings is available too.

**Comment by shadowmourne** [comment]
I don't know if nvidia-settings can replace nvidia-smi cause I don't have Tesla, Quadro or GRID products to test.
So I think it's better to keep these both available.

**Comment by Mic92** [comment]
Merged, thanks.

**Pull request merged**
