### PR TITLE
README: missing bracket in `batwidget` example

### PR DESCRIPTION
**Pull request by JulianVolodia**
Added missing bracket and remove one whitespace (it would be more consistent)
Signed-off-by: Julian Volodia <julianvolodia@gmail.com>

---

Hi, I noticed when testing batt's stat wibox box ;)

BTW, why on the page (http://git.sysphere.org/vicious/about/) there is not mentioned about github repository? (and at all - "...you can send me..." - is ambiguous :-) )

Have a nice day! :)

### CODE REVIEW

**Comment by Mic92** [comment]
merged in https://github.com/Mic92/vicious/commit/240de45c4196f87bae3dc24f1a21e596eafabd80

This is not the official vicious github repo.
However I review patches send them via email upstream.
So I am like a proxy between anrxc and those who never used git-send-email before.

**Comment by JulianVolodia** [comment]
> So I am like a proxy between anrxc and those who never used git-send-email before.
... so it's better to send patches via email only, yep?

**Comment by Mic92** [comment]
You can if you want sent the patches directly to 
  Adrian C. (anrxc) <anrxc@sysphere.org>
However sometimes it might take some days before you get a response.

**Comment by JulianVolodia** [comment]
I just asking for more preferred way by Devs for doing this and where the feedback could be given :) I was thinking the GH is better place to do it.

**Pull request closed without merging**
